version: "3.9"

networks:
  default:
    name: traefik
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - ./data/qbittorrent:/config
      - $DATADIR/$DOWNLOADS_FOLDER:/data/downloads
      - $USERDIR:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 2
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
      - traefik.http.routers.qbittorrent.tls.certresolver=letsencryptresolver
