version: "3.9"
networks:
  default:
    # name: nginx-network
    name: traefik
    external: true


services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
        TZ: $TZ
        PUID: $PUID
        PGID: $PGID
    volumes:
      - ./data/jackett:/config
      - $DATADIR/$DOWNLOADS_FOLDER:/downloads
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.entrypoints=websecure
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
      - traefik.http.routers.jackett.service=jackett
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.http.routers.jackett.tls.certresolver=letsencryptresolver